#pragma once

#include <iostream>
#include <ctime>
#include "Player.h"
#include "Planets.h"

class Game
{
	private:
		sf::RenderWindow* window; // used for creating our window 
		sf::VideoMode videoMode; // used for editing the window
		bool endGame;
		bool startGame;
		sf::Event ev; // Events generated by mouse or keyboard
		sf::Image logo;
		int points;
		sf::Font font;
		sf::Text hpText;
		sf::Text pointsText;
		sf::Text gameOverText;

		// Player Object
		Player player;

		std::vector <Planets> planets;
		float spawnTimerMax;
		float spawnTimer;
		int maxPlanets;
		
		// Init functions : initializes variables
		void initWindow();
		void initVariable();
		void initFont();
		void initText();
	public:
		// Constructors and Destructors
		Game();
		~Game();

	
		// Accessors : Get Variables from this class

		// Modifiers : Modifies Variables fron this class

		// Functions
		void pollEvents(); // events which happen by user input
		const bool running() const;

		void updateCollision();
		void update(); // update each and everything
		void render(); // render each and everything
		void spawnPlanets(); // spawning the planets
		const int randPlanetsType();
		void renderUI(sf::RenderTarget* target); // Renderning the text
		void updateUI();

		void gameOver(sf::RenderTarget* target);
};